export const messageTypes = {
    ADD_USER: "ADD_USER",

    ADD_MESSAGE: "ADD_MESSAGE",

    GET_CONVERSATION: "GET_CONVERSATION",

    GET_MESSAGE: "GET_MESSAGE",

    UPDATE_MESSAGE: "UPDATE_MESSAGE",

    DELETE_MESSAGE: "DELETE_MESSAGE",

    DELETE_CONVERSATION: "DELETE_CONVERSATION",

    USER_ONLINE_OFFLINE: "USER_ONLINE_OFFLINE",
}