export const notifyTypes = {
    GET_NOTIFIES: "GET_NOTIFIES",
    GET_NOTIFIES_SUCCESS: "GET_NOTIFIES_SUCCESS",
    GET_NOTIFIES_FAILD: "GET_NOTIFIES_FAILD",

    CREATE_NOTIFIES: "CREATE_NOTIFIES",
    REMOVE_NOTIFIES: "REMOVE_NOTIFIES",

    UPDATE_NOTIFY: "UPDATE_NOTIFY",

    UPDATE_SOUND: "UPDATE_SOUND",

    DELETE_ALL_NOTIFIES: "DELETE_ALL_NOTIFIES"
}