export const PostTypes = {
    CREATE_POST: "CREATE_POST",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_FAILD: "CREATE_POST_FAILD",
    CREATE_POST_RESET: "CREATE_POST_RESET",

    GET_POST: "GET_POST",
    GET_POST_SUCCESS: "GET_POST_SUCCESS",
    GET_POST_FAILD: "GET_POST_FAILD",

    UPDATE_POST: "UPDATE_POST",
    UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
    UPDATE_POST_FAILD: "UPDATE_POST_FAILD",

    POST_DTAILS: "POST_DTAILS",
    POST_DTAILS_SUCCESS: "POST_DTAILS_SUCCESS",
    POST_DTAILS_FAILD: "POST_DTAILS_FAILD",

    GET_DISCOVER_POSTS: "GET_DISCOVER_POSTS",
    GET_DISCOVER_POSTS_SUCCESS: "GET_DISCOVER_POSTS_SUCCESS",
    GET_DISCOVER_POSTS_FAILD: "GET_DISCOVER_POSTS_FAILD",
    UPDATE_DISCOVER_POSTS: "UPDATE_DISCOVER_POSTS",

    UPDATE_POST_PAGE: "UPDATE_POST_PAGE",

    DELETE_POST:"DELETE_POST",
}