export const Types = {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILD: "USER_LOGIN_FAILD",
    USER_LOGIN_RESET: "USER_LOGIN_RESET",

    USER_VALIDATE: "USER_VALIDATE",
    USER_LOGOUT: "USER_LOGOUT",

    USER_PROFILE: "USER_PROFILE",
    USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
    USER_PROFILE_FAILD: "USER_PROFILE_FAILD",
    USER_PROFILE_IDS: "USER_PROFILE_IDS",

    USER_PROFILE_POSTS: "USER_PROFILE_POSTS",
    USER_PROFILE_POSTS_SUCCESS: "USER_PROFILE_POSTS_SUCCESS",
    USER_PROFILE_POSTS_FAILD: "USER_PROFILE_POST_FAILD",

    USER_PROFILE_UPDATE: "USER_PROFILE_UPDATE",
    USER_PROFILE_UPDATE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
    USER_PROFILE_UPDATE_FAILD: "USER_PROFILE_UPDATE_FAILD",
    USER_PROFILE_UPDATE_RESET: "USER_PROFILE_UPDATE_RESET",

    FOLLOW: "FOLLOW",
    UNFOLLOW: "UNFOLLOW",

    USER_FOLLOW: "USER_FOLLOW",
    USER_FOLLOW_SUCCESS: "USER_FOLLOW_SUCCESS",
    USER_FOLLOW_FAILD: "USER_FOLLOW_FAILD",

    PROFILE_UPDATE_PAGE: "PROFILE_UPDATE_PAGE",

    SUGGESTION_USER: "SUGGESTION_USER",
    SUGGESTION_USER_SUCCESS: "SUGGESTION_USER_SUCCESS",
    SUGGESTION_USER_FAILD: "SUGGESTION_USER_FAILD",
}